from lipidlibrarian.lipid.Nomenclature import Level


LIPID_NAME_TEST_MATRIX = {
    "PC": {
        Level.sum_lipid_species: {
            "name": "PC 38:1",
            "expects": {
                "parse_lipidlynxx": True,
                "parse_goslin": True,
                "has_alex123_results": True,
                "has_alex123_fragments": False,
                "has_swisslipids_results": True,
                "has_swisslipids_mass": True,
                "has_swisslipids_adducts": True,
                "has_swisslipids_reactions": False,
                "has_lipidmaps_results": False,
                "has_lipidmaps_mass": False,
                "has_lipidmaps_adducts": False,
                "has_lipidmaps_smiles": False,
                "has_lipidmaps_inchi": False,
                "has_linex_results": True,
                "has_lion_results": True,
            },
        },
        Level.molecular_lipid_species: {
            "name": "PC 18:1_20:0",
            "expects": {
                "parse_lipidlynxx": True,
                "parse_goslin": True,
                "has_alex123_results": True,
                "has_alex123_fragments": True,
                "has_swisslipids_results": True,
                "has_swisslipids_mass": True,
                "has_swisslipids_adducts": True,
                "has_swisslipids_reactions": False,
                "has_lipidmaps_results": False,
                "has_lipidmaps_mass": False,
                "has_lipidmaps_adducts": False,
                "has_lipidmaps_smiles": False,
                "has_lipidmaps_inchi": False,
                "has_linex_results": True,
                "has_lion_results": True,
            },
        },
        Level.structural_lipid_species: {
            "name": "PC 18:1/20:0",
            "expects": {
                "parse_lipidlynxx": True,
                "parse_goslin": True,
                "has_alex123_results": True,
                "has_alex123_fragments": True,
                "has_swisslipids_results": True,
                "has_swisslipids_mass": True,
                "has_swisslipids_adducts": True,
                "has_swisslipids_reactions": False,
                "has_lipidmaps_results": False,
                "has_lipidmaps_mass": False,
                "has_lipidmaps_adducts": False,
                "has_lipidmaps_smiles": False,
                "has_lipidmaps_inchi": False,
                "has_linex_results": True,
                "has_lion_results": True,
            },
        },
        Level.isomeric_lipid_species: {
            "name": "PC 18:1(9Z)/20:0",
            "expects": {
                "parse_lipidlynxx": True,
                "parse_goslin": True,
                "has_alex123_results": True,
                "has_alex123_fragments": True,
                "has_swisslipids_results": True,
                "has_swisslipids_mass": True,
                "has_swisslipids_adducts": True,
                "has_swisslipids_reactions": False,
                "has_lipidmaps_results": True,
                "has_lipidmaps_mass": True,
                "has_lipidmaps_adducts": True,
                "has_lipidmaps_smiles": True,
                "has_lipidmaps_inchi": True,
                "has_linex_results": True,
                "has_lion_results": True,
            },
        },
    },
    "PE": {
        Level.sum_lipid_species: {
            "name": "PE 36:2",
            "expects": {
                "parse_lipidlynxx": True,
                "parse_goslin": True,
                "has_alex123_results": True,
                "has_alex123_fragments": False,
                "has_swisslipids_results": True,
                "has_swisslipids_mass": True,
                "has_swisslipids_adducts": True,
                "has_swisslipids_reactions": False,
                "has_lipidmaps_results": False,
                "has_lipidmaps_mass": False,
                "has_lipidmaps_adducts": False,
                "has_lipidmaps_smiles": False,
                "has_lipidmaps_inchi": False,
                "has_linex_results": True,
                "has_lion_results": True,
            },
        },
        Level.molecular_lipid_species: {
            "name": "PE 18:0_18:2",
            "expects": {
                "parse_lipidlynxx": True,
                "parse_goslin": True,
                "has_alex123_results": True,
                "has_alex123_fragments": True,
                "has_swisslipids_results": True,
                "has_swisslipids_mass": True,
                "has_swisslipids_adducts": True,
                "has_swisslipids_reactions": False,
                "has_lipidmaps_results": False,
                "has_lipidmaps_mass": False,
                "has_lipidmaps_adducts": False,
                "has_lipidmaps_smiles": False,
                "has_lipidmaps_inchi": False,
                "has_linex_results": True,
                "has_lion_results": True,
            },
        },
        Level.structural_lipid_species: {
            "name": "PE 18:0/18:2",
            "expects": {
                "parse_lipidlynxx": True,
                "parse_goslin": True,
                "has_alex123_results": True,
                "has_alex123_fragments": True,
                "has_swisslipids_results": True,
                "has_swisslipids_mass": True,
                "has_swisslipids_adducts": True,
                "has_swisslipids_reactions": False,
                "has_lipidmaps_results": False,
                "has_lipidmaps_mass": False,
                "has_lipidmaps_adducts": False,
                "has_lipidmaps_smiles": False,
                "has_lipidmaps_inchi": False,
                "has_linex_results": True,
                "has_lion_results": True,
            },
        },
        Level.isomeric_lipid_species: {
            "name": "PE 18:0/18:1(9Z)",
            "expects": {
                "parse_lipidlynxx": True,
                "parse_goslin": True,
                "has_alex123_results": True,
                "has_alex123_fragments": True,
                "has_swisslipids_results": True,
                "has_swisslipids_mass": True,
                "has_swisslipids_adducts": True,
                "has_swisslipids_reactions": False,
                "has_lipidmaps_results": True,
                "has_lipidmaps_mass": True,
                "has_lipidmaps_adducts": True,
                "has_lipidmaps_smiles": True,
                "has_lipidmaps_inchi": True,
                "has_linex_results": True,
                "has_lion_results": True,
            },
        },
    },
    "PS": {
        Level.sum_lipid_species: {
            "name": "PS 36:1",
            "expects": {
                "parse_lipidlynxx": True,
                "parse_goslin": True,
                "has_alex123_results": True,
                "has_alex123_fragments": False,
                "has_swisslipids_results": True,
                "has_swisslipids_mass": True,
                "has_swisslipids_adducts": True,
                "has_swisslipids_reactions": False,
                "has_lipidmaps_results": False,
                "has_lipidmaps_mass": False,
                "has_lipidmaps_adducts": False,
                "has_lipidmaps_smiles": False,
                "has_lipidmaps_inchi": False,
                "has_linex_results": True,
                "has_lion_results": True,
            },
        },
        Level.molecular_lipid_species: {
            "name": "PS 18:0_18:1",
            "expects": {
                "parse_lipidlynxx": True,
                "parse_goslin": True,
                "has_alex123_results": True,
                "has_alex123_fragments": True,
                "has_swisslipids_results": True,
                "has_swisslipids_mass": True,
                "has_swisslipids_adducts": True,
                "has_swisslipids_reactions": False,
                "has_lipidmaps_results": False,
                "has_lipidmaps_mass": False,
                "has_lipidmaps_adducts": False,
                "has_lipidmaps_smiles": False,
                "has_lipidmaps_inchi": False,
                "has_linex_results": True,
                "has_lion_results": True,
            },
        },
        Level.structural_lipid_species: {
            "name": "PS 18:0/18:1",
            "expects": {
                "parse_lipidlynxx": True,
                "parse_goslin": True,
                "has_alex123_results": True,
                "has_alex123_fragments": True,
                "has_swisslipids_results": True,
                "has_swisslipids_mass": True,
                "has_swisslipids_adducts": True,
                "has_swisslipids_reactions": False,
                "has_lipidmaps_results": False,
                "has_lipidmaps_mass": False,
                "has_lipidmaps_adducts": False,
                "has_lipidmaps_smiles": False,
                "has_lipidmaps_inchi": False,
                "has_linex_results": True,
                "has_lion_results": True,
            },
        },
        Level.isomeric_lipid_species: {
            "name": "PS 18:0/18:1(9Z)",
            "expects": {
                "parse_lipidlynxx": True,
                "parse_goslin": True,
                "has_alex123_results": True,
                "has_alex123_fragments": True,
                "has_swisslipids_results": True,
                "has_swisslipids_mass": True,
                "has_swisslipids_adducts": True,
                "has_swisslipids_reactions": False,
                "has_lipidmaps_results": True,
                "has_lipidmaps_mass": True,
                "has_lipidmaps_adducts": True,
                "has_lipidmaps_smiles": True,
                "has_lipidmaps_inchi": True,
                "has_linex_results": True,
                "has_lion_results": True,
            },
        },
    },
    "ST 27:1;O": {
        Level.isomeric_lipid_species: {
            "name": "ST 27:1;O",
            "expects": {
                "parse_lipidlynxx": True,
                "parse_goslin": True,
                "has_alex123_results": True,
                "has_alex123_fragments": True,
                "has_swisslipids_results": True,
                "has_swisslipids_mass": True,
                "has_swisslipids_adducts": True,
                "has_swisslipids_reactions": False,
                "has_lipidmaps_results": True,
                "has_lipidmaps_mass": True,
                "has_lipidmaps_adducts": True,
                "has_lipidmaps_smiles": True,
                "has_lipidmaps_inchi": True,
                "has_linex_results": True,
                "has_lion_results": True,
            },
        },
    },
    "ST 27:1": {
        Level.structural_lipid_species: {
            "name": "ST 27:1/18:1",
            "expects": {
                "parse_lipidlynxx": True,
                "parse_goslin": True,
                "has_alex123_results": True,
                "has_alex123_fragments": True,
                "has_swisslipids_results": True,
                "has_swisslipids_mass": True,
                "has_swisslipids_adducts": True,
                "has_swisslipids_reactions": False,
                "has_lipidmaps_results": True,  # CE(18:1)
                "has_lipidmaps_mass": True,
                "has_lipidmaps_adducts": True,
                "has_lipidmaps_smiles": True,
                "has_lipidmaps_inchi": True,
                "has_linex_results": True,
                "has_lion_results": True,
            },
        },
    },
    "Cer": {
        Level.sum_lipid_species: {
            "name": "Cer 36:2;O2",
            "expects": {
                "parse_lipidlynxx": True,
                "parse_goslin": True,
                "has_alex123_results": True,
                "has_alex123_fragments": True,
                "has_swisslipids_results": True,  # SLM:000391259
                "has_swisslipids_mass": True,
                "has_swisslipids_adducts": True,
                "has_swisslipids_reactions": False,
                "has_lipidmaps_results": False,
                "has_lipidmaps_mass": False,
                "has_lipidmaps_adducts": False,
                "has_lipidmaps_smiles": False,
                "has_lipidmaps_inchi": False,
                "has_linex_results": True,
                "has_lion_results": True,
            },
        },
        Level.structural_lipid_species: {
            "name": "Cer 18:1;O2/18:1",
            "expects": {
                "parse_lipidlynxx": True,
                "parse_goslin": True,
                "has_alex123_results": True,
                "has_alex123_fragments": True,
                "has_swisslipids_results": True,  # SLM:000392136
                "has_swisslipids_mass": True,
                "has_swisslipids_adducts": True,
                "has_swisslipids_reactions": False,
                "has_lipidmaps_results": False,
                "has_lipidmaps_mass": False,
                "has_lipidmaps_adducts": False,
                "has_lipidmaps_smiles": False,
                "has_lipidmaps_inchi": False,
                "has_linex_results": True,
                "has_lion_results": True,
            },
        },
        Level.isomeric_lipid_species: {
            "name": "Cer 18:1;O2/18:1(9Z)",
            "expects": {
                "parse_lipidlynxx": True,
                "parse_goslin": True,
                "has_alex123_results": True,
                "has_alex123_fragments": True,
                "has_swisslipids_results": False,
                "has_swisslipids_mass": False,
                "has_swisslipids_adducts": False,
                "has_swisslipids_reactions": False,
                "has_lipidmaps_results": False,  # LMSP02010003  # Goslin issue
                "has_lipidmaps_mass": False,
                "has_lipidmaps_adducts": False,
                "has_lipidmaps_smiles": False,
                "has_lipidmaps_inchi": False,
                "has_linex_results": True,
                "has_lion_results": True,
            },
        },
    },
    "TG": {
        Level.sum_lipid_species: {
            "name": "TG 54:2",
            "expects": {
                "parse_lipidlynxx": True,
                "parse_goslin": True,
                "has_alex123_results": True,
                "has_alex123_fragments": False,
                "has_swisslipids_results": True,  # SLM:000308322
                "has_swisslipids_mass": True,
                "has_swisslipids_adducts": True,
                "has_swisslipids_reactions": False,
                "has_lipidmaps_results": False,
                "has_lipidmaps_mass": False,
                "has_lipidmaps_adducts": False,
                "has_lipidmaps_smiles": False,
                "has_lipidmaps_inchi": False,
                "has_linex_results": True,
                "has_lion_results": True,
            },
        },
        Level.molecular_lipid_species: {
            "name": "TG 16:1_18:1_20:0",
            "expects": {
                "parse_lipidlynxx": True,
                "parse_goslin": True,
                "has_alex123_results": True,
                "has_alex123_fragments": True,
                "has_swisslipids_results": True,  # SLM:000326427
                "has_swisslipids_mass": True,
                "has_swisslipids_adducts": True,
                "has_swisslipids_reactions": False,
                "has_lipidmaps_results": False,
                "has_lipidmaps_mass": False,
                "has_lipidmaps_adducts": False,
                "has_lipidmaps_smiles": False,
                "has_lipidmaps_inchi": False,
                "has_linex_results": True,
                "has_lion_results": True,
            },
        },
        Level.structural_lipid_species: {
            "name": "TG 16:1/18:1/20:0",
            "expects": {
                "parse_lipidlynxx": True,
                "parse_goslin": True,
                "has_alex123_results": True,
                "has_alex123_fragments": True,
                "has_swisslipids_results": True,  # SLM:000369410
                "has_swisslipids_mass": True,
                "has_swisslipids_adducts": True,
                "has_swisslipids_reactions": False,
                "has_lipidmaps_results": False,
                "has_lipidmaps_mass": False,
                "has_lipidmaps_adducts": False,
                "has_lipidmaps_smiles": False,
                "has_lipidmaps_inchi": False,
                "has_linex_results": True,
                "has_lion_results": True,
            },
        },
        Level.isomeric_lipid_species: {
            "name": "TG 16:1(9Z)/18:1(9Z)/20:0",
            "expects": {
                "parse_lipidlynxx": True,
                "parse_goslin": True,
                "has_alex123_results": True,
                "has_alex123_fragments": True,
                "has_swisslipids_results": True,
                "has_swisslipids_mass": True,
                "has_swisslipids_adducts": True,
                "has_swisslipids_reactions": False,
                "has_lipidmaps_results": True,
                "has_lipidmaps_mass": True,
                "has_lipidmaps_adducts": True,
                "has_lipidmaps_smiles": True,
                "has_lipidmaps_inchi": True,
                "has_linex_results": True,
                "has_lion_results": True,
            },
        },
    },
}
